# Generated by Django 3.1.3 on 2021-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userss',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
