# Generated by Django 3.1.3 on 2021-03-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210304_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userss',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userss',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
